# Generated by Django 2.0.7 on 2018-07-21 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_auto_20180720_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='trainings.Language'),
        ),
    ]
