# Generated by Django 2.0.7 on 2018-07-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_auto_20180721_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='name',
        ),
    ]
