# Generated by Django 2.0.7 on 2018-07-24 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0007_auto_20180721_1307'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('name', 'language')},
        ),
    ]
