# Generated by Django 2.0.7 on 2018-07-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0008_auto_20180724_0656'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('name', 'language')},
        ),
    ]
