# Generated by Django 2.0.7 on 2018-07-27 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0014_auto_20180726_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='post',
            name='no_of_ratings',
        ),
    ]
