# Generated by Django 2.0.7 on 2018-07-27 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0015_auto_20180727_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=500, null=True)),
                ('rating', models.PositiveIntegerField()),
                ('avg_rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('rated_on', models.DateTimeField(auto_now_add=True)),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
                ('rated_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='trainings.Post')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('rated_by', 'rated_post')},
        ),
    ]
