# Generated by Django 2.0.7 on 2018-07-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0016_auto_20180727_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
